version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  
  pre_build:
    commands:
      - echo Dep install started on `date`
      - npm ci
      - npx cypress verify

  build:
    commands:
      - echo Build started on `date`
      - npx cypress run --reporter junit --reporter-options "mochaFile=results.xml"

artifacts:
  files:
    - cypress/results/**/*
    - cypress/screenshots/**/*
    - cypress/videos/**/*
    - cypress.config.ts
    - package.json
    - package-lock.json
    - tsconfig.json
    - README.md

reports:
  test-report:
    files:
      - "results.xml"
    file-format: "JUNITXML"